# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run metrics

on:
  workflow_dispatch:
  workflow_run:
    branches:
      - "metrics"
jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    defaults:
      run:
        working-directory: ./metrics
    steps:
      - uses: actions/checkout@v4
      - uses: stefanzweifel/git-auto-commit-action@v5
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Gather metrics
        env: # Set the secret as an input
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install github_traffic_stats
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          gts maria-mcparland:$ACCESS_TOKEN 'snippets' 'save_csv'
          ls
      - name: Run merge script
        run: |
          ./merge.sh clone-stats.csv ./merged-file-clone.csv      
          ./merge.sh traffic-stats.csv ./merged-file-traffic.csv
          ./merge.sh referrer-stats.csv ./merged-file-referrer.csv
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply metrics changes
