name: OAuth Integration tests

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
    test-python:
        runs-on: ubuntu-latest
        defaults:
          run: 
            working-directory: './oauth-integration/python'
        steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: 'Create env file'
          run: |
            cp ../.env.example ./.env    
        - name: Test 
          run: |
            python test_oauth.py
    test-js:
        runs-on: ubuntu-latest
        defaults:
            run: 
              working-directory: './oauth-integration/node-js'
        strategy:
            matrix:
              node-version: [14.x, 16.x, 18.x]
        steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'yarn'
            cache-dependency-path: './oauth-integration/node-js/yarn.lock'
        - name: Install depdendencies
          run: yarn install --frozen-lockfile
        - name: 'Create env file'
          run: |
            cp ../.env.example ./.env
        - name: Tests
          run: yarn test
    test-java:
        runs-on: ubuntu-latest
        defaults:
            run: 
              working-directory: './oauth-integration/java'
        steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
        - name: Build and test with Maven
          run: mvn -B package --file pom.xml